Network:
  vpc:
    maxAzs: 2
    natGateways: 0
    ipv6enabled: true
  alb:
    listener:
      certificateArn: "arn:aws:acm:ap-northeast-1:048132608410:certificate/bb183acc-7a83-4ff4-8c11-4c8df960b0e2"
    targetHealthCheck: 
      enabled: true
      interval: 30 # unit: seconds
      path: "/hello"
      timeout: 5 # unit: seconds
      healthyThresholdCount: 5
      unhealthyThresholdCount: 2
    deregistrationDelay: 60 # unit: seconds

Ecs:
  memoryLimitMiB: 512
  cpu: 256
  family: rest-api
  container:
    name: RestApiContainer
    environment:
      STAGE: lab  
  service:
    desiredCount: 0
    minHealthyPercent: 100
    maxHealthyPercent: 200
    circuitBreakerRollback: false
    assignPublicIp: true  # Value is true and ECS Service Subnet type is public, Value is false and ECS Service Subnet type is private.

Deployment:
  type: BlueGreen # RollingUpdate or BlueGreen